### ISSUE TITLE
Testing but not recognizing any body

### ISSUE THREAD

**Issue by Bardo91** [mgb45/mkfbodytracker_pdaf#2]
Hi,
I am testing your code but I am not able to make it work with me. I did some modifications to make it work with catkin and ros-kinetic in ubuntu 16.04 and OpenCV-3.3.1, but haven't touch the code. This is what I got:
![image](https://user-images.githubusercontent.com/3602335/34960518-79d90aec-fa3b-11e7-870d-f006cafadbe7.png)

I also tried it with the dataset you provide and works randomly:
![image](https://user-images.githubusercontent.com/3602335/34960639-fa3205f4-fa3b-11e7-8d25-7dc766590ee3.png)

![image](https://user-images.githubusercontent.com/3602335/34960645-fd2a1c10-fa3b-11e7-9a3b-4e7f823eeed7.png)

![image](https://user-images.githubusercontent.com/3602335/34960649-008e5bd2-fa3c-11e7-83ba-d0cf67f2952e.png)

Could you give me any advice?

**Comment by mgb45** [comment]
Hi,

This code isn't really maintained at this point, since there are many more effective approaches to human pose estimation available nowadays, for example [this.](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation) The primary contribution of this work was the 2D to 3D pose tracking node

_mkfbodytracker_pdaf_

This node takes a subset of 2D joint measurements and users a pose tracking approach to infer the 3D pose of the person. The primary limiting factor for this node is the input 2D measurements provided by the face and hand detection - here I just use some carefully tuned ones for demonstration. Judging by your picture, this is what seems to be failing - the face detector isn't picking you up, which is why the pose is failing. You could try modifying the parameters in the face detector node,

_facetracking_

but ideally you want to replace the measurement nodes with something more modern, like a convnet joint detector that you can sample from to feed into the tracker.

If you can share a bag file I can probably tune the parameters to make these work for you, but as I mentioned the input measurement nodes were never intended to provide a stable and robust solution, only a demonstration of the pose tracker.

**Comment by Bardo91** [comment]
Hi, 
Thank you very much for your answer. I know there are other methods using DNN, I was inspecting other possibilities that I found :). I will try to feed your module as you said with the result of another detector.
Thanks again. I am closing the issue
